import {
  DEFAULT_PROMPT_LANGUAGE,
  type PromptDetailDto,
  type PromptJudgmentRulesDto,
  type PromptLanguageDto,
  type PromptListCustomLabelDto,
  type PromptListItemDto,
  type PromptOutputSchemaDto,
  type PromptStatusDto,
  type PromptVariableDto,
  type PromptVariableTypeDto,
  type PromptVersionLabelDto,
  type PromptVersionDto,
  type PromptVersionStatusDto,
} from '@proofhound/shared';
import type { TranslationKey } from '../../i18n';

export type PromptVersionStatus = PromptVersionStatusDto;
export type PromptResourceStatus = PromptStatusDto;
export type PromptVariableType = PromptVariableTypeDto;
export type PromptLanguage = PromptLanguageDto;

export interface PromptVariable {
  name: string;
  type: PromptVariableType;
  required: boolean;
  description: string;
  datasetField: string;
  selected: boolean;
}

export interface PromptOutputField {
  key: string;
  value: string;
  isJudgment: boolean;
}

export const PROMPT_JUDGMENT_FALLBACK_KEY = 'expected_output';
export const PROMPT_JUDGMENT_FALLBACK_VALUE = 'expected_output';
export const PROMPT_JUDGMENT_VALUE_SEPARATOR = ' 或 ';

export interface PromptJudgmentRule {
  id: string;
  field: string;
  operator: string;
  value: string;
  description: string;
}

export interface PromptVersion {
  id: string;
  version: number;
  status: PromptVersionStatus;
  labels: PromptVersionLabelDto[];
  author: string;
  createdAt: string;
  changeReason: string;
  autoGenerated?: boolean;
  referencedBy?: string;
  parentVersion?: number;
  promptLanguage: PromptLanguage;
  body: string;
  variables: PromptVariable[];
  outputFields: PromptOutputField[];
  judgmentRules: PromptJudgmentRule[];
  frozen: boolean;
}

export interface ProjectPrompt {
  id: string;
  name: string;
  latestVersion: number;
  canaryVersion?: number;
  onlineVersion?: number;
  status: PromptVersionStatus;
  resourceStatus: PromptResourceStatus;
  archivedAt: string | null;
  owner: string;
  createdAt: string;
  updatedAt: string;
  tags: string[];
  customLabels: PromptListCustomLabelDto[];
  body: string;
  variables: PromptVariable[];
  outputFields: PromptOutputField[];
  judgmentRules: PromptJudgmentRule[];
  versions: PromptVersion[];
  activeReferences: number;
  defaultDatasetId: string | null;
  defaultDatasetName: string | null;
}

export const PROMPT_VARIABLE_TYPE_LABEL_KEYS: Record<PromptVariableType, TranslationKey> = {
  text: 'prompts.variableType.text',
  image: 'prompts.variableType.image',
  image_url: 'prompts.variableType.imageUrl',
  image_base64: 'prompts.variableType.imageBase64',
  number: 'prompts.variableType.number',
};

function toPromptVariable(variable: PromptVariableDto): PromptVariable {
  return {
    name: variable.name,
    type: variable.type,
    required: variable.required,
    description: variable.description ?? '',
    datasetField: variable.datasetField ?? variable.name,
    selected: true,
  };
}

function toOutputFields(outputSchema: PromptOutputSchemaDto | null | undefined): PromptOutputField[] {
  const fields = outputSchema?.fields as unknown;
  if (!Array.isArray(fields)) return [];

  return fields
    .filter((field): field is Record<string, unknown> => Boolean(field) && typeof field === 'object')
    .map((field) => ({
      key: String(field.key ?? field.name ?? ''),
      value: String(field.value ?? field.description ?? ''),
      isJudgment: Boolean(field.isJudgment ?? field.is_decision ?? field.judgment),
    }))
    .filter((field) => field.key.length > 0);
}

export function deriveJudgmentField(args: {
  expectedOutputFieldName: string | null;
  categoryLabels: string[];
}): PromptOutputField {
  const key = args.expectedOutputFieldName?.trim() || PROMPT_JUDGMENT_FALLBACK_KEY;
  const value =
    args.categoryLabels.length > 0
      ? args.categoryLabels.join(PROMPT_JUDGMENT_VALUE_SEPARATOR)
      : PROMPT_JUDGMENT_FALLBACK_VALUE;
  return { key, value, isJudgment: true };
}

export function upsertJudgmentField(fields: PromptOutputField[], judgment: PromptOutputField): PromptOutputField[] {
  const others = fields.filter((field) => !field.isJudgment);
  return [judgment, ...others];
}

function toJudgmentRules(judgmentRules: PromptJudgmentRulesDto): PromptJudgmentRule[] {
  if (!judgmentRules) return [];

  const rawRules = judgmentRules.rules;
  if (Array.isArray(rawRules)) {
    return rawRules
      .filter((rule): rule is Record<string, unknown> => Boolean(rule) && typeof rule === 'object')
      .map((rule, index) => ({
        id: String(rule.id ?? `rule-${index + 1}`),
        field: String(rule.field ?? ''),
        operator: String(rule.operator ?? judgmentRules.mode ?? 'match'),
        value: String(rule.value ?? rule.expected_field ?? ''),
        description: String(rule.description ?? ''),
      }))
      .filter((rule) => rule.field.length > 0);
  }

  const decisionField = judgmentRules.decision_field ?? judgmentRules.decisionField ?? 'label';
  const expectedField = judgmentRules.expected_field ?? judgmentRules.expectedField ?? 'expected_output';
  return [
    {
      id: 'rule-primary',
      field: String(decisionField),
      operator: String(judgmentRules.mode ?? 'exact_match'),
      value: String(expectedField),
      description: String(judgmentRules.description ?? ''),
    },
  ];
}

function toPromptVersion(version: PromptVersionDto, versions: PromptVersionDto[]): PromptVersion {
  const parent = version.parentVersionId
    ? versions.find((item) => item.id === version.parentVersionId)?.versionNumber
    : undefined;

  return {
    id: version.id,
    version: version.versionNumber,
    status: version.status,
    labels: version.labels ?? [],
    author: version.createdByDisplayName ?? '',
    createdAt: version.createdAt,
    changeReason: version.changeReason ?? '',
    autoGenerated: Boolean(version.generatedByOptimizationId),
    parentVersion: parent,
    promptLanguage: version.promptLanguage ?? DEFAULT_PROMPT_LANGUAGE,
    body: version.body,
    variables: version.variables.map(toPromptVariable),
    outputFields: toOutputFields(version.outputSchema),
    judgmentRules: toJudgmentRules(version.judgmentRules),
    frozen: version.isFrozen,
  };
}

function getTags(prompt: PromptListItemDto) {
  const tags: string[] = [prompt.latestVersionStatus];
  if (prompt.currentOnlineVersionNumber) tags.push('online');
  if (!prompt.currentOnlineVersionNumber && prompt.latestVersionStatus === 'editable') tags.push('new');
  return Array.from(new Set(tags));
}

export function toProjectPromptListItem(prompt: PromptListItemDto): ProjectPrompt {
  return {
    id: prompt.id,
    name: prompt.name,
    latestVersion: prompt.latestVersionNumber,
    canaryVersion: prompt.currentCanaryVersionNumber ?? undefined,
    onlineVersion: prompt.currentOnlineVersionNumber ?? undefined,
    status: prompt.latestVersionStatus,
    resourceStatus: prompt.status,
    archivedAt: prompt.archivedAt,
    owner: prompt.createdByDisplayName ?? '',
    createdAt: prompt.createdAt,
    updatedAt: prompt.updatedAt,
    tags: getTags(prompt),
    customLabels: prompt.customLabels ?? [],
    body: '',
    variables: [],
    outputFields: [],
    judgmentRules: [],
    versions: [],
    activeReferences: prompt.activeReferences,
    defaultDatasetId: prompt.defaultDatasetId,
    defaultDatasetName: prompt.defaultDatasetName,
  };
}

export function toProjectPrompt(prompt: PromptDetailDto): ProjectPrompt {
  const versions = prompt.versions
    .map((version) => toPromptVersion(version, prompt.versions))
    .sort((left, right) => right.version - left.version);
  const latestVersion = versions[0];

  return {
    ...toProjectPromptListItem(prompt),
    body: latestVersion?.body ?? '',
    variables: latestVersion?.variables ?? [],
    outputFields: latestVersion?.outputFields ?? [],
    judgmentRules: latestVersion?.judgmentRules ?? [],
    versions,
  };
}

export function getPromptSearchText(prompt: ProjectPrompt) {
  return [
    prompt.name,
    prompt.owner,
    prompt.tags.join(' '),
    prompt.customLabels.map((label) => label.name).join(' '),
    prompt.variables.map((variable) => variable.name).join(' '),
  ]
    .join(' ')
    .toLowerCase();
}
